version: "3"

services:
  api:
    container_name: api
    env_file: 
      - ./deploy/docker/env/backend.env
    environment: 
      POSTGRES_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
      NODE_ENV: staging
      WAIT_HOSTS: postgres:5432, redis:6379
    build: 
      context: .
      dockerfile: ./deploy/docker/backend.Dockerfile
    depends_on:
      - redis
      - postgres
    links:
     - postgres
     - redis
    ports:
      - "3000:3000"

  web:
    container_name: nginx
    build: 
      context: .
      dockerfile: ./deploy/docker/nginx.Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./dist:/var/www/html
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"

  postgres:
    container_name: psql
    hostname: postgres
    restart: always
    image: "postgres:11"
    env_file:
      - ./deploy/docker/env/postgres.env
    volumes:
      - ./store/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: nc -z localhost 5432

  redis:
    container_name: redis
    hostname: redis
    image: "redis"
    ports:
      - "6379:6379"