# https://learnk8s.io/deploying-nodejs-kubernetes
# https://www.magalix.com/blog/nodejs-app-sample-from-docker-to-kubernetes-cluster

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: eventi/backend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PRODUCTION
              value: "true"
            - name: PG_USER
              value: "root"
            - name: PG_PASS
              value: "12345"
            - name: PRIVATE_KEY
              value: "test"
            - name: EMAIL_ADDRESS
              value: "m@cass.si"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - name: tcp
      port: 3000
      targetPort: 3000
