apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : frontend-app
    spec:
      containers:
        - name: frontend-app
          image: eventi/frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: service-name
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value  