version: "3.9"
services:
  web:
    build: ../backend
    ports:
      - "5000:5000"
  angular:
    build: ../frontend
    ports:
      - "8080:8080"
    redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:11"