export enum Genre {
  Drama,
  Play,
  Comedy,
  Tragedy,
  Melodrama,
  Farce,
  Tragicomedy,
  Burlesque,
  MoralityPlay,
  History,
  Poetry,
  Slapstick,
  Epic,
  ComedyOfManners,
  Encyclopedia,
  Romanticism,
  ComedyDrama,
  KitchenSinkRealism,
  Prose,
  Parody,
  Allegory,
  BourgeoisTragedy,
  ClosetDrama,
  PsychologicalThriller,
  GreekMythology,
  LiterayRealism,
  Pastoral,
  TheatreCriticism,
}

export const GenreMap: { [index in Genre]: string } = {
  [Genre.Drama]: 'Drama',
  [Genre.Play]: 'Play',
  [Genre.Comedy]: 'Comedy',
  [Genre.Tragedy]: 'Tragedy',
  [Genre.Melodrama]: 'Melodrama',
  [Genre.Farce]: 'Farce',
  [Genre.Tragicomedy]: 'Tragicomedy',
  [Genre.Burlesque]: 'Burlesque',
  [Genre.MoralityPlay]: 'Morality Play',
  [Genre.History]: 'History',
  [Genre.Poetry]: 'Poetry',
  [Genre.Slapstick]: 'Slapstick',
  [Genre.Epic]: 'Epic',
  [Genre.ComedyOfManners]: 'Comedy Of Manners',
  [Genre.Encyclopedia]: 'Encyclopedia',
  [Genre.Romanticism]: 'Romanticism',
  [Genre.ComedyDrama]: 'Comedy Drama',
  [Genre.KitchenSinkRealism]: 'Kitchen Sink Realism',
  [Genre.Prose]: 'Prose',
  [Genre.Parody]: 'Parody',
  [Genre.Allegory]: 'Allegory',
  [Genre.BourgeoisTragedy]: 'Bourgeois Tragedy',
  [Genre.ClosetDrama]: 'Closet Drama',
  [Genre.PsychologicalThriller]: 'Psychological Thriller',
  [Genre.GreekMythology]: 'Greek Mythology',
  [Genre.LiterayRealism]: 'Literay Realism',
  [Genre.Pastoral]: 'Pastoral',
  [Genre.TheatreCriticism]: 'Theatre Criticism',
};
