export enum TheatreGenre {
  Drama,
  Play,
  Comedy,
  Tragedy,
  Melodrama,
  Farce,
  Tragicomedy,
  Burlesque,
  MoralityPlay,
  History,
  Poetry,
  Slapstick,
  Epic,
  ComedyOfManners,
  Encyclopedia,
  Romanticism,
  ComedyDrama,
  KitchenSinkRealism,
  Prose,
  Parody,
  Allegory,
  BourgeoisTragedy,
  ClosetDrama,
  PsychologicalThriller,
  GreekMythology,
  LiterayRealism,
  Pastoral,
  TheatreCriticism,
}

export const TheatreGenreMap: { [index in TheatreGenre]: string } = {
  [TheatreGenre.Drama]: 'Drama',
  [TheatreGenre.Play]: 'Play',
  [TheatreGenre.Comedy]: 'Comedy',
  [TheatreGenre.Tragedy]: 'Tragedy',
  [TheatreGenre.Melodrama]: 'Melodrama',
  [TheatreGenre.Farce]: 'Farce',
  [TheatreGenre.Tragicomedy]: 'Tragicomedy',
  [TheatreGenre.Burlesque]: 'Burlesque',
  [TheatreGenre.MoralityPlay]: 'Morality Play',
  [TheatreGenre.History]: 'History',
  [TheatreGenre.Poetry]: 'Poetry',
  [TheatreGenre.Slapstick]: 'Slapstick',
  [TheatreGenre.Epic]: 'Epic',
  [TheatreGenre.ComedyOfManners]: 'Comedy Of Manners',
  [TheatreGenre.Encyclopedia]: 'Encyclopedia',
  [TheatreGenre.Romanticism]: 'Romanticism',
  [TheatreGenre.ComedyDrama]: 'Comedy Drama',
  [TheatreGenre.KitchenSinkRealism]: 'Kitchen Sink Realism',
  [TheatreGenre.Prose]: 'Prose',
  [TheatreGenre.Parody]: 'Parody',
  [TheatreGenre.Allegory]: 'Allegory',
  [TheatreGenre.BourgeoisTragedy]: 'Bourgeois Tragedy',
  [TheatreGenre.ClosetDrama]: 'Closet Drama',
  [TheatreGenre.PsychologicalThriller]: 'Psychological Thriller',
  [TheatreGenre.GreekMythology]: 'Greek Mythology',
  [TheatreGenre.LiterayRealism]: 'Literay Realism',
  [TheatreGenre.Pastoral]: 'Pastoral',
  [TheatreGenre.TheatreCriticism]: 'Theatre Criticism',
};
