# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend

on:
  push:
    branches: [ release-* ]
  pull_request:
    branches: [ dev, release-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'

    - name: Test Interfaces
      working-directory: ./interfaces
      run: |
        npm install
        npm install typescript -g
        tsc

    - name: Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm run test
