# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ release-*, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  interfaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Compile interfaces
        working-directory: ./interfaces
        run: |
          npm install
          tsc

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Lint backend
        working-directory: ./backend
        run: |
          npm ci
          npm run lint

      - name: Transpile backend
        working-directory: ./backend
        run: |
          npm install typescript -g
          tsc

      - name: Test Backend
        working-directory: ./backend
        run: |
          npm run test
